## **Librerias**

In [1]:
import pandas as pd
import numpy as np

## **1. Foundations for efficiencies**

### **1.1 Built-ins Functions**

**range**

Genera secuencias

In [49]:
a = [i for i in range(0, 10)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

**enumerate**

Crea indices para un objeto iterable

In [26]:
letters = ['A', 'B', 'C', 'D', 'E']

In [37]:
dict(enumerate(letters, start=0))

{0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E'}

**map**

Aplica una función a los elementos de un objeto iterable

In [51]:
b = lambda x: x * 10

In [52]:
list(map(b, a))

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [54]:
list(map(lambda x: x*2, a))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

### **1.2 The power of NumPy arrays**

In [56]:
nums_np = np.array(range(1, 11))
nums_np

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Si queremos aplicar realizar alguna función con los elementos de nuestro array podemos aplicarla directamente 

In [75]:
nums_np**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

Podemos utilizar condicionales para definir los elemetos de un array

In [84]:
array_1 = np.array([-1, 2, 3, -4])
array_1[(array_1>0)]

array([2, 3])

## **2. Timing and profiling code**

In [2]:
import line_profiler

### **2.1 Examining runtime**

In [9]:
%timeit rand_nums = np.random.rand(1000)
# rand_nums

15.6 µs ± 565 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [19]:
# %%time
%timeit rand_nums = np.random.rand(100000000)

1.75 s ± 201 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
def convert_units(heroes, heights, weights):
    new_hts = [ht * 0.39370 for ht in heights]
    new_wts = [wt * 2.40462 for wt in weights]
    
    hero_data = {}
    
    for i,hero in enumerate(heroes):
        hero_data[hero] = (new_hts, new_wts)
    
    return hero_data

In [9]:
heroes = ['Batman', 'Spiderman', 'WonderWoman']
hts = np.array([188.0, 191.0, 183.0])
wts = np.array([95, 101, 74])

In [10]:
convert_units(heroes, hts, wts)

{'Batman': ([74.01559999999999, 75.19669999999999, 72.0471],
  [228.4389, 242.86662, 177.94188]),
 'Spiderman': ([74.01559999999999, 75.19669999999999, 72.0471],
  [228.4389, 242.86662, 177.94188]),
 'WonderWoman': ([74.01559999999999, 75.19669999999999, 72.0471],
  [228.4389, 242.86662, 177.94188])}

In [11]:
%load_ext line_profiler

In [19]:
%lprun -f convert_units convert_units(heroes, hts, wts)

Timer unit: 1e-07 s

Total time: 0.0002118 s
File: C:\Users\jmart\AppData\Local\Temp/ipykernel_11380/1233246566.py
Function: convert_units at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
     1                                           def convert_units(heroes, heights, weights):
     2         1        473.0    473.0     22.3      new_hts = [ht * 0.39370 for ht in heights]
     3         1       1215.0   1215.0     57.4      new_wts = [wt * 2.40462 for wt in weights]
     4                                               
     5         1         49.0     49.0      2.3      hero_data = {}
     6                                               
     7         4        196.0     49.0      9.3      for i,hero in enumerate(heroes):
     8         3        140.0     46.7      6.6          hero_data[hero] = (new_hts, new_wts)
     9                                               
    10         1         45.0     45.0      2.1      return hero_data

### **2.2 Examining memory usage**

In [16]:
import sys
import memory_profiler

In [13]:
nums_list = [*range(1000)]

## Saber cuanto espacio de memoria ocupa
sys.getsizeof(nums_list)

9104

In [14]:
nums_array = np.array(range(1000))

## Saber cuanto espacio de memoria ocupa
sys.getsizeof(nums_array)

4104