## Librerias

In [1]:
import pandas as pd
import numpy as np

## **1. Foundations for efficiencies**

### **1.1 Built-ins Functions**

**range**

Genera secuencias

In [49]:
a = [i for i in range(0, 10)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
letters = ['A', 'B', 'C', 'D', 'E']

**enumerate**

Crea indices para un objeto iterable

In [37]:
dict(enumerate(letters, start=0))

{0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E'}

**map**

Aplica una función a los elementos de un objeto iterable

In [51]:
b = lambda x: x * 10

In [52]:
list(map(b, a))

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [54]:
list(map(lambda x: x*2, a))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

### **1.2 The power of NumPy arrays**

In [56]:
nums_np = np.array(range(1, 11))
nums_np

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Si queremos aplicar realizar alguna función con los elementos de nuestro array podemos aplicarla directamente 

In [75]:
nums_np**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

Podemos utilizar condicionales para definir los elemetos de un array

In [84]:
array_1 = np.array([-1, 2, 3, -4])
array_1[(array_1>0)]

array([2, 3])

## **2. Timing and profiling code**

### **2.1 Examining runtime**

In [9]:
%timeit rand_nums = np.random.rand(1000)
# rand_nums

15.6 µs ± 565 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [19]:
# %%time
%timeit rand_nums = np.random.rand(100000000)

1.75 s ± 201 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
